### ISSUE TITLE
Enabling clickjack protection settings interferes with visualforce page

### ISSUE THREAD

**Issue by datapharmer** [danhowellnz/DeclarativeScheduler#4]
Checking "Enable clickjack protection for customer Visualforce pages with standard headers" in the Salesforce Security Session Settings causes the lookup report scheduling visualforce to fail.

ScheduleReportSelector apex:page should declare: `showHeader="false" applyHtmlTag="false"`
since api version 38 or higher is used.

Documentation: https://help.salesforce.com/articleView?id=000230608&type=1&language=en_US

**Comment by danhowellnz** [comment]
Thanks @datapharmer 
I'll add the headers in. Do you need a new managed package link?

**Comment by danhowellnz** [comment]
I updated the install link
/packaging/installPackage.apexp?p0=04t7F000002kHqf

**Comment by datapharmer** [comment]
Awesome, thanks! I tested and it works as expected. Much appreciated!
