### ISSUE TITLE
What happens if batch size < report limit?

### ISSUE THREAD

**Issue by datapharmer** [danhowellnz/DeclarativeScheduler#5]
If the report has 1000 lines but batch size is 100 will it be chunked into 10 pieces that execute or will only the first 100 get processed?

**Comment by danhowellnz** [comment]
Yes batch is the chunk size. So a batch size of 1 means it processes 1 record at a time and a batch size of 100 it processes 100 at once. 

This is different from the report size. Your report of 1000 lines will be in 10 chunks (batches) if the batch size is 100.
